### PR TITLE
Room capacity fix

### PR DESCRIPTION
**Pull request by Feverfew**
## What does this PR do?
Fixes bug in roombookings/rooms endpoint when capacity is not of type float.
Adds tests to confirm that invalid input is handled correctly

## ✅ Pull Request checklist

- [ ] Is this code complete?
- [ ] Are tests done/modified?
- [ ] Are docs written for this PR? (if applicable)

## 🚨 Is this a breaking change for API clients?
No

## :squirrel: Deploy notes
None

### CODE REVIEW

**Comment by ChristopherHammond13** [comment]
@Feverfew Does room capacity have to be a float?

**Comment by Feverfew** [comment]
> @Feverfew Does room capacity have to be a float?

For some reason it is a float in the DB

> @Feverfew Does room capacity have to be a float?

The field is a float itself but we wouldn't get a type error later if I changed it to be an int. However, if someone were to input 55.5, how would you like the API to handle this?

**Comment by ChristopherHammond13** [comment]
@Feverfew I think we should just convert the float to an int and work that way? Working in floats _feels_ wrong given that you can't have half people :P @zipy124 what do you think, Mr CTO?

**Comment by zipy124** [comment]
@Feverfew @ChristopherHammond13 I definitely agree with chris here. Since we're working with a discrete variable we should just cast to int. Float feels very wrong.

**Pull request merged**
