### PR TITLE
Slimming treatment for dashboard static assets

### PR DESCRIPTION
**Pull request by hueyy**
## What does this PR do?
* Avoids serving all assets in a single 4.3MB file (see issue #916)
* There is now a shared file with vendor (JS) assets that can be cached between pages
* CSS has been separated into a separate file for each page (so changes to JS only might not invalidate a cached CSS file)
* Images are served separately so they can be cached separately
* Removed `webpack-serve` because it has been deprecated + it doesn't seem necessary because Django serves up static assets just fine in development
* Added a Django plugin - `django-webpack-loader` which reads the webpack manifest and dynamically updates the CSS & JS imports in Django templates every time webpack rebuilds.

## ✅ Pull Request checklist

- [x] Is this code complete?
[NA] Are tests done/modified?
- [x] Are docs written for this PR? (if applicable)

## 🚨 Is this a breaking change for API clients?
No

## :squirrel: Deploy notes
I'm not sure what the deployment process is, so I'm not certain if any changes need to be made there. However, `npm run build` and `./manage.py runserver collectstatic` continue to function the same way, so it seems unlikely any changes will be required.

CLARIFICATION: `django-webpack-loader` does not poll in production when `DEBUG` is False. This is set by `'CACHE': not DEBUG` in `settings.py` meaning when `DEBUG` is False, it will read the stats file only once and cache the result.

### CODE REVIEW

**Comment by hueyy** [comment]
Also, I realise Travis is failing. This seems to be because webpack is not building the bundle. `npm run build` should be run to build the static assets and generate the missing `webpack-stats.json`.

**Comment by ChristopherHammond13** [comment]
This is awesome! It builds so much quicker too.
Just a couple of comments:
- It looks like we need to specify production for `npm run build` somewhere as WebPack gives a warning. I'm concerned that in the future there might be a breaking change where `production` is not the default.
- Is there a way of slimming this down further, or placing asserts outside of the JS? >1MB per file is still pretty high (albeit *way* smaller than before)
image

**Comment by hueyy** [comment]
It's the total (non-image) assets that exceed 1MB, not the page-specific JS/CSS files. The page-specific JS/CSS files are less than 50kB each (yay).

image

The largest JS file is the vendor one which contains millions of dependencies, the largest of which is probably (momentjs is ~150kB I think). Fortunately, this file is re-used between pages so it can be cached after the getStarted page is loaded. We could reduce the size of the vendor JS file further by:

* tree shaking and eliminating all the unused functions in the libraries we import (but this requires we use only ES6 modules and import a bit more selectively)
* carefully scrutinising our existing dependencies to see if any can be eliminated or replaced with a more lightweight version (e.g. momentjs with day.js/luxon/etc)

I could go ahead with ^ but this will involve changes to the main React code, which we might want to do in a separate PR.

We could also reduce the total asset size by optimising the very large but very beautiful logoCover (I suspect it could be much smaller as a JPEG).

One other thing, we should definitely gzip all the things (at least the JS/CSS). I can setup webpack to build gzipped assets but I'll need to update the S3 metadata (probably as simple as setting Content-Encoding=gzip)

**Comment by ChristopherHammond13** [comment]
@hueyy Interesting, thanks so much for clarifying all that! We can open an issue for ES6 migration and general slimming of assets. Until then, I'm happy to merge this as it's awesome!

**Comment by ChristopherHammond13** [comment]
@hueyy How can we fix the Travis-CI Build?
```
3.14s$ coverage run --source='.' --omit='*migrations*' manage.py test --testrunner 'uclapi.custom_test_runner.NoDbTestRunner' --settings=uclapi.settings_mocked
/home/travis/build/uclapi/uclapi/backend/uclapi/common/helpers.py:13: UserWarning: Not reading /home/travis/build/uclapi/uclapi/backend/uclapi/.env - it doesn't exist.
  rd(path)
...............E................................................/home/travis/build/uclapi/uclapi/backend/uclapi/roombookings/helpers.py:99: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: None QuerySet.
  paginator = Paginator(all_bookings, pagination)
..............................
======================================================================
ERROR: test_post_agreement (dashboard.tests.DashboardTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpack_loader/loader.py", line 26, in _load_assets
    with open(self.config['STATS_FILE'], encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/build/uclapi/uclapi/backend/uclapi/webpack-stats.json'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/build/uclapi/uclapi/backend/uclapi/dashboard/tests.py", line 63, in test_post_agreement
    res = self.client.post('/dashboard/', {'agreement': 'True'})
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/test/client.py", line 548, in post
    secure=secure, **extra)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/test/client.py", line 350, in post
    secure=secure, **extra)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/test/client.py", line 416, in generic
    return self.request(**r)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/test/client.py", line 501, in request
    six.reraise(*exc_info)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/utils/six.py", line 686, in reraise
    raise value
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/travis/build/uclapi/uclapi/backend/uclapi/dashboard/views.py", line 146, in dashboard
    'initial_data': initial_data
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/template/library.py", line 203, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpack_loader/templatetags/webpack_loader.py", line 12, in render_bundle
    tags = utils.get_as_tags(bundle_name, extension=extension, config=config, attrs=attrs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpack_loader/utils.py", line 45, in get_as_tags
    bundle = _get_bundle(bundle_name, extension, config)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpack_loader/utils.py", line 23, in _get_bundle
    bundle = get_loader(config).get_bundle(bundle_name)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpack_loader/loader.py", line 60, in get_bundle
    assets = self.get_assets()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpack_loader/loader.py", line 39, in get_assets
    return self._load_assets()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/webpack_loader/loader.py", line 32, in _load_assets
    self.config['STATS_FILE']))
OSError: Error reading /home/travis/build/uclapi/uclapi/backend/uclapi/webpack-stats.json. Are you sure webpack has generated the file and the path is correct?
```

**Comment by hueyy** [comment]
Hound is still upset about something, but I'm not sure what.

**Pull request merged**
