### PR TITLE
Fairuse

### PR DESCRIPTION
**Pull request by hennersz**
## What does this PR do?
Adds fair use agreement page and makes user agree to it before they can view their apps

## ✅ Pull Request checklist

- [ ✅] Is this code complete?
- [✅ ] Are tests done/modified?

## 📃 Link to PR updating documentation (if applicable)

https://github.com/uclapi/apiDocs/pulls

## 🚨 Is this a breaking change for API clients?
No

## :squirrel: Deploy notes
Need to run migrations as part of deployment and build frontend files for new styles in production mode

## Anything else

### CODE REVIEW

**Comment by wilhelmklopp** [comment]
Awesome, really great stuff @hennersz 💯 
Could you add a screenshot of what it looks like right now? Or even better a Gif of the flow?
http://gifbrewery.com/ is awesome for that.

@anirudhpillai could code review?

@ChristopherHammond13 is staging ready for this?

**Comment by ChristopherHammond13** [comment]
@hennersz can you check that this is all correct now? I needed to merge master into the branch and rebuild a bunch of things

**Comment by hennersz** [comment]
It seems the tests are failing in travis due to being unable to insert into the db, @jermenkoo do you know the proper way to add db actions for tests to be run in travis

**Comment by ChristopherHammond13** [comment]
Turns out there are encoding problems with this. Working on a fix now.

**Pull request merged**
