### PR TITLE
Fix tests to account for changed serialisation

### PR DESCRIPTION
**Pull request by xoneco**
We updated the code, and didn't change the tests. With the CI, that should hopefully never happen again :D

@jermenkoo all tests pass for me locally

### CODE REVIEW

**Comment by jermenkoo** [comment]
LGTM, can be merged by Chris.

**Comment by xoneco** [comment]
@jermenkoo I was gonna wait for the CI to work and give this a green check before merging

**Comment by jermenkoo** [comment]
@xoneco alright boss

**Comment by ChristopherHammond13** [comment]
Merging now :)

**Comment by xoneco** [comment]
@ChristopherHammond13 clearly disagrees haha

**Pull request merged**
