### PR TITLE
Adds error message for invalid oauth callback url

### LINKED ISSUE #945: OAuth: No Error Message for Invalid Callback URLs
1) Create a new OAuth app in the Dashboard
2) Save an invalid callback URL, e.g. localhost
3) No Error
4) ???
5) Failure

### PR DESCRIPTION
**Pull request by zipy124**
## What does this PR do?
Exactly what it says on the tin.

## ✅ Pull Request checklist

- [ ] Is this code complete?
- [ ] Are tests done/modified?
- [ ] Are docs written for this PR? (if applicable)

## 🚨 Is this a breaking change for API clients?
no

## :squirrel: Deploy notes
n/A

## Anything else
closes #945

### CODE REVIEW

**Comment by ChristopherHammond13** [comment]
LGTM 👍 
Is there a screenshot of how this looks before I merge?

**Comment by zipy124** [comment]
@ChristopherHammond13 
screenshot from 2019-02-24 00-45-15

**Comment by ChristopherHammond13** [comment]
@zipy124 Nice work. Perhaps we should explain to the user what's wrong with their URL too? i.e. we should tell them that HTTPS is required and localhost is not acceptable.

**Comment by zipy124** [comment]
@ChristopherHammond13 I guess we can add that, that would require back-end modification though. Currently i'm just passing through the currently exposed error. Maybe make that an additional issue and PR? Since this front-end will now pass through any error message returned via json so no more front-end changes need to be made to accommodate that change.

**Pull request merged**
