### PR TITLE
sort apps by creation date

### PR DESCRIPTION
**Pull request by hennersz**

### CODE REVIEW

**Comment by jermenkoo** [comment]
Looks good to me.

**Comment by xoneco** [comment]
does still need build files?

**Comment by hennersz** [comment]
I wasn't sure if having different built files on separate branches would cause loads of merge conflicts so i didn't commit them

**Comment by hennersz** [comment]
so this will need to be rebuilt on the server

**Comment by xoneco** [comment]
@hennersz so we merge the other one first and then add build files to this (maybe with a rebase)

OR @ChristopherHammond13 has to run the build on the box.
Chris do you know the steps?

Ideally we should be consistent tho. So either no build files in version control, or all build files in version control

**Comment by ChristopherHammond13** [comment]
@xoneco do I just need to do a `collectstatic` once I git pull, or is there more to this?

**Comment by hennersz** [comment]
tbh id rather no build files in version control
@ChristopherHammond13 wait until I create the production build scripts and I will add instructions

**Comment by ChristopherHammond13** [comment]
@hennersz It would be ideal to not have to do static site generation on the servers otherwise we'll need to install bundler / ruby /etc.

**Comment by xoneco** [comment]
this is more of a #future #biggerpicture opinion for later down the line, but imho all builds for prod should happen as part of the build/deployment pipeline, not locally.

**Comment by hennersz** [comment]
also you only need node to build the frontend

**Comment by hennersz** [comment]
but for now I will just build production code to a separate directory

**Comment by hennersz** [comment]
actually this is going to make everything more complicated

**Pull request merged**
