### PR TITLE
Redis-based Last-Modified Header

### LINKED ISSUE #839: Cached Data Age Headers
We have a lot of data that is updated regularly from other sources and cached at our end. We should tell our developers programmatically how old this data is so that they can plan their apps around our updating.

This will also help us to build #838 because if data is too old then we know that we have an issue with our Cron server (i.e. the data is not being updated as expected).

We can use the [Expires](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Expires) header to implement this.

### PR DESCRIPTION
**Pull request by ChristopherHammond13**
## What does this PR do?
Adds Last-Modified Header

## ✅ Pull Request checklist

- [x] Is this code complete?
- [x] Are tests done/modified?
- [x] Are docs written for this PR? (if applicable)

## 🚨 Is this a breaking change for API clients?
No

## :squirrel: Deploy notes
Just deploy!

## Anything else
closes #839

### CODE REVIEW

**Comment by zipy124** [comment]
Seems good to me. I'm not sure the testing involving current_time is correct? We assert in the comments that we can't be sure it executes within the second, therefore the test could fail if we execute at say 16:59:59 and the other timestamp is 16:60:00. the seconds are technically not within 1 of another, maybe add a modulo to wrap around at 60 and 00?

**Comment by zipy124** [comment]
@ChristopherHammond13 We should probably add some information about the header details to the documentation? Where shall we put it?

**Comment by zipy124** [comment]
@ChristopherHammond13 Timetable events draw from both the timetable_gencache and gencache(through the _get_timetable_events function). Which header should they therefore take?

**Comment by zipy124** [comment]
> Good point. We can probably do it by generating all datetimes for within 3 seconds of the current one and asserting that they're within range. We'd hit the same issue if we executed over midnight, for example.

Sounds like a good solution to me.

**Comment by ChristopherHammond13** [comment]
I'll merge this once I've fixed up the test as per how we discussed it on Slack @zipy124

**Pull request merged**
