### PR TITLE
Degree API

### PR DESCRIPTION
**Pull request by Feverfew**
## What does this PR do?
Adds 1 (or 2 :P) endpoints which allows retrieval of courses taught by a department, and subsequently, modules taught on a particular courses, which can be filtered with various query parameters.
These endpoints are also documented on the website.
Implements #918 

## ✅ Pull Request checklist

- [] Is this code complete?
- [] Are tests done/modified?
- [] Are docs written for this PR? (if applicable)

## 🚨 Is this a breaking change for API clients?
No

## :squirrel: Deploy notes
Need to run migrations as part of deployment
Need to update the cache?

### CODE REVIEW

**Comment by ChristopherHammond13** [comment]
I will gladly review this once the 43 Hound violations have been looked into :P

**Comment by zipy124** [comment]
> I will gladly review this once the 43 Hound violations have been looked into :P

Reduced this to 23, mostly line length ones left. I cba to fix these before I sleep

**Comment by Feverfew** [comment]
Idk what the last hound ones are complaining about because they are compliant to pep8.

**Comment by zipy124** [comment]
> Idk what the last hound ones are complaining about because they are compliant to pep8.

refer to this https://github.com/PyCQA/pycodestyle/issues/386 . Hound seems to prefer we do solution #3 instead of solution #1 . Tbh kinda makes sense.

**Comment by Feverfew** [comment]
MB, forget that rebasing on an already existing PR would make this a lot messier.

**Pull request merged**
