### PR TITLE
fixing prettyjson for bookings endpoint

### PR DESCRIPTION
**Pull request by jermenkoo**
## What does this PR do?
Prettifying did not work for `bookings` endpoint previously.

## ✅ Pull Request checklist

- [x] Is this code complete?
- [x] Are tests done/modified?

## 📃 Link to PR updating documentation (if applicable)

https://github.com/uclapi/apiDocs/pulls

## 🚨 Is this a breaking change for API clients?
No.

## :squirrel: Deploy notes
No.

## Anything else
No.

### CODE REVIEW

**Comment by ChristopherHammond13** [comment]
Is this tested locally as working, and have you regression tested it on the other endpoints? If so, I'll merge (along with my new AUP)

**Comment by jermenkoo** [comment]
TravisCI does not want to show but the build passes -> https://travis-ci.org/uclapi/uclapi/builds/237920660

**Comment by jermenkoo** [comment]
@ChristopherHammond13 one second, restarted build hoping codecov would pick it up as well (they are experiencing issues as well due to GitHub's increased latency)

**Comment by jermenkoo** [comment]
@ChristopherHammond13 can be merged.

**Pull request merged**
