### PR TITLE
fix bug that caused the helper function to fail

### PR DESCRIPTION
**Pull request by Faiz**

### CODE REVIEW

**Comment by xoneco** [comment]
Some tests for this function would be amazing 😁

**Comment by abdulfaizp** [comment]
okie okie okie

**Comment by ChristopherHammond13** [comment]
@abdulfaizp is this all ready to go now?

**Comment by Faiz** [comment]
@wilhelmklopp  @ChristopherHammond13 now can I die in peace?

**Comment by wilhelmklopp** [comment]
Looks good 👍 Well done @Faiz The more tests you write, the less painful it becomes :)
Congrats on that username also!

@jermenkoo Could you CR this pls

**Comment by wilhelmklopp** [comment]
@ChristopherHammond13 could you merge and deploy this please :)

**Comment by ChristopherHammond13** [comment]
@wilhelmklopp staging is dodgy atm. Straight to prod or wait for staging?

**Comment by wilhelmklopp** [comment]
@ChristopherHammond13 let's wait for staging :)

**Comment by ChristopherHammond13** [comment]
@wilhelmklopp just to make you _so_ happy, I'm merging into master and I'm going to send it to staging.

**Pull request merged**
