### PR TITLE
Dockerise uclapi

### PR DESCRIPTION
**Pull request by Maaarcocr**
One of the pain points of developing uclapi is setting up your local environment. This should not be the case.

I've added a Dockerfile, a docker-compose.yml and some bash scripts. This let us run everything with just one command: `docker-compose up`.

This install all the Oracle things that are needed in the container so that you don't need to contaminate your machine directly. 

P.S. when you run it like this you don't have to worry about rebuilding the container if you change files!

### CODE REVIEW

**Comment by wilhelmklopp** [comment]
Super excited about this. This should make a lot of things much easier especially our deployment pipeline.

Thanks for putting in the work @Maaarcocr ✨

**Comment by ChristopherHammond13** [comment]
This is great! We have some internal installation scripts that I can augment this with (maybe over the weekend once our pre-hackathon work is done). It'll be super helpful for our eventual pipeline  ❤️

**Comment by ChristopherHammond13** [comment]
This is still on my to do list. Production is unlikely to be dockerised (for now), but certainly local testing would be far easier with a configured Dockerfile.

**Comment by ChristopherHammond13** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.uclapi.com/job/UCLAPI/290/
Jenkins statics successfully built.

**Comment by ChristopherHammond13** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.uclapi.com/job/UCLAPI/291/
Jenkins statics successfully built.

**Comment by ChristopherHammond13** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://jenkins.uclapi.com/job/UCLAPI/425/
Jenkins statics successfully built.

**Comment by ChristopherHammond13** [comment]
Just a quick update that I have taken this on and I'm making a decent amount of headway with Docker-ising out production deployment thanks to your leg up!

I'll have a commit soon containing a far more complete set of configuration files (with certs, etc. redacted, of course, for security reasons). This includes the Shibboleth and Nginx configuration stages which were, prior to now, entirely private.

Watch this space!

**Comment by ChristopherHammond13** [comment]
This has been replaced by #264. Thanks so much @Maaarcocr!!

**Pull request closed without merging**
