### PR TITLE
Enabled and fixed temp token tests. Add common/helpers.py tests

### PR DESCRIPTION
**Pull request by zipy124**
## What does this PR do?
Enabled and fixed temp-token tests
Also Adds test to see if headers are added correctly to http responses.
## ✅ Pull Request checklist

- [ ] Is this code complete?
- [ ] Are tests done/modified?
- [ ] Are docs written for this PR? (if applicable)

## 🚨 Is this a breaking change for API clients?
No

## :squirrel: Deploy notes
Run the new migration to delete the un-needed model

### CODE REVIEW

**Comment by ChristopherHammond13** [comment]
Great code!
Just a heads up though that the `TemporaryToken` model is now no longer used, and we instead put temp tokens in Redis to avoid filling up the database (this was done in #222, which was only merged and completed very recently).

It might be worth us stripping out all the code for the `TemporaryToken` model, but for now I'm happy to keep tests in place for it.

**Comment by ChristopherHammond13** [comment]
(In fact, if you want to strip all that legacy code out in this PR feel free, because then there'll be less code to test too)

**Comment by zipy124** [comment]
> (In fact, if you want to strip all that legacy code out in this PR feel free, because then there'll be less code to test too)

I suspected there was a reason for this, i was very confused. I'll try to strip out all the legacy code and their tests!

**Comment by zipy124** [comment]
@ChristopherHammond13 I've stripped out the legacy model. The tests for expired tokens has also been removed temporarily while i re-make it work with redis.

**Pull request merged**
