### PR TITLE
Dashboard fixes

### PR DESCRIPTION
**Pull request by hennersz**
Fixed the issues with buttons on the create app form being different sizes and made the form close after being submitted successfully. Errors for ajax requests are now shown in UI rather than in console

### CODE REVIEW

**Comment by ChristopherHammond13** [comment]
@xoneco can I merge this?

**Comment by xoneco** [comment]
@ChristopherHammond13 yup, if you've tested it locally and it works 👍 

@hennersz not sure if this one is done actually or still WIP?

**Comment by hennersz** [comment]
I haven't added the autofocus for the add app modal but I can add that in a different pull request later

**Comment by xoneco** [comment]
Ok, cool let's do that in a separate one.
Small PRs are a good thing 👍

**Pull request merged**
