### PR TITLE
Fix/marketplace phones

### PR DESCRIPTION
**Pull request by TuxedoFish**
## What does this PR do?
The marketplace was rendering oddly on phones due to to the meta viewport tag not being set in the template so added that and then fiddled with padding and stuff on phones

* Want to add a slider for the images in a future PR because the screenshots still look off right now but want to work on that seperately

## ✅ Pull Request checklist

- [ ] Is this code complete?
- [ ] Are tests done/modified?
- [ ] Are docs written for this PR? (if applicable)

## 🚨 Is this a breaking change for API clients?
No

## :squirrel: Deploy notes
Npm

## Anything else

screencapture-localhost-8000-marketplace-2019-12-05-10_30_00 (1)

screencapture-localhost-8000-marketplace-uclassistant-2019-12-05-10_30_15 (1)

### CODE REVIEW

**Comment by hueyy** [comment]
woah you're really on a roll

**Comment by TuxedoFish** [comment]
> woah you're really on a roll

haha! 👀 No lecture Thursdays so thought I would fix this and the blog and icon issues you pointed out!

**Comment by hueyy** [comment]
I think you left a `this.DEBUGGING = true` in `frontend/src/components/layout/containers/Row.jsx`, but otherwise all good.

**Comment by TuxedoFish** [comment]
> I think you left a `this.DEBUGGING = true` in `frontend/src/components/layout/containers/Row.jsx`, but otherwise all good.

fixed!

**Pull request merged**
