### PR TITLE
Remove files needed for initial insert

### PR DESCRIPTION
**Pull request by xoneco**
## What does this PR do?
Remove files we needed initially for the coordinate insert, but longer require.
Hence, cleanup for clarity and cleanliness.

## ✅ Pull Request checklist

- [x] Is this code complete?
n/a Are tests done/modified?

## 📃 Link to PR updating documentation (if applicable)
n/a

## 🚨 Is this a breaking change for API clients?
No

## :squirrel: Deploy notes
n/a

### CODE REVIEW

**Comment by ChristopherHammond13** [comment]
We need to discuss the best way of dynamically generating and gathering initial data sets. We should be able to deploy a production environment from scratch with ease :)

**Comment by xoneco** [comment]
As discussed in person:

- The single source of truth should be the db, not a JSON file
- If we make any updates to this, it will happen via Django Admin or something similar, not via another JSON file
- We **do** need to think about how to replicate this sort of constant data from one environment to another when setting it up initially, but that solution is not blocked by this PR

**Comment by xoneco** [comment]
Crowdsourcing would be very cool!
That's potentially a whole nother project with a huge scope 😄 

But would be super exciting and I want to do it 🌮

**Comment by abdulfaizp** [comment]
I think a lot of the problems in UCL can be solved by crowdsourcing a lot of stuff. Things like room location, free space, water fountains etc.

**Comment by ChristopherHammond13** [comment]
@xoneco @abdulfaizp did we come to a conclusion on this? Shall I merge?

**Comment by xoneco** [comment]
@ChristopherHammond13 This can be merged, yes. But we need some kind of db/table replication mechanism.

**Comment by ChristopherHammond13** [comment]
@xoneco we already have replication on the production database via Amazon RDS (Multi-AZ deployment; we essentially have a replica on standby in another availability zone ready for a switchover if the main deployment fails). Is this enough? We could have a replica setup if you're concerned but I think this is enough.

**Pull request merged**
